version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: python_web_service
    ports:
      - "8000:8000"  # Replace the second port with the one your Python web service listens on
      - "5432:5432"
    volumes:
      - ./:/app  # Mount your Python web service code to the container
      - ~/data:/data  # Mount a volume to store the database
    environment:
      - DATABASE_LOCATION=/data/db.sqlite3
      - TEMPLATES_DIR=/app/src/templates
      - BOT_TOKEN=${BOT_TOKEN}  # Replace with your Telegram bot token
      - DB_USER=${DB_USER}  # Replace with your Telegram bot token
      - DB_PASSWORD=${DB_PASSWORD}  # Replace with your Telegram bot token
    command: ["python", "src/app.py"]  # Replace with the correct path to your web service script

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: scraper_job
    ports:
      - "5432:5432"
    volumes:
      - ./:/app  # Mount your scraper code to the container
      - ~/data:/data  # Mount a volume to store the database
    environment:
      - DATABASE_LOCATION=/data/db.sqlite3
      - BOT_TOKEN=${BOT_TOKEN}  # Replace with your Telegram bot token
      - DB_USER=${DB_USER}  # Replace with your Telegram bot token
      - DB_PASSWORD=${DB_PASSWORD}  # Replace with your Telegram bot token
    command: ["python", "-u", "src/scraper.py"]  # Replace with the correct path to your scrap.py script

  reporter:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: reporter_job
    ports:
      - "5432:5432"
    volumes:
      - ./:/app  # Mount your scraper code to the container
      - ~/data:/data  # Mount a volume to store the database
    environment:
      - DATABASE_LOCATION=/data/db.sqlite3
      - BOT_TOKEN=${BOT_TOKEN}  # Replace with your Telegram bot token
      - DB_USER=${DB_USER}  # Replace with your Telegram bot token
      - DB_PASSWORD=${DB_PASSWORD}  # Replace with your Telegram bot token
    command: ["python", "-u", "src/reporter.py"]  # Replace with the correct path to your scrap.py script
