"""add user_type column

Revision ID: 530fff098233
Revises: 37d4b4eeedfd
Create Date: 2023-09-17 16:02:06.448945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import Enum
from src.models.sqlmodels import UserType, SQLModel

# revision identifiers, used by Alembic.
revision: str = '530fff098233'
down_revision: Union[str, None] = '37d4b4eeedfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

UserType: Enum = Enum(
    UserType,
    name="usertype",
    create_constraint=True,
    metadata=SQLModel.metadata,
    validate_strings=True,
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    UserType.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('user_type', sa.Enum('user', 'recruiter', 'expert', name='usertype'), nullable=False, server_default='recruiter'))
    op.alter_column('user', 'user_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_type')
    UserType.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
