"""add_user_type

Revision ID: c86c9bab7056
Revises: 37d4b4eeedfd
Create Date: 2023-09-17 01:17:47.184443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86c9bab7056'
down_revision: Union[str, None] = '37d4b4eeedfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.TEXT(), nullable=False, server_default='recruiter'))
    op.alter_column('user', 'user_type', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###
